#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Daniel Bastos'
        hostname: ubuntu-desktop
        username: daniel
        password: '$y$j9T$5pAN1/ncUajtWgf7sXvvz0$QL5UPd8QwMI0KVtUHuZ8wmTj35jMLQ1DK7KR2GI/0R4'
    locale: en_US.UTF-8
    keyboard:
        layout: br
    timezone: "America/Bahia"   
    packages:
        - libreoffice
        - git
        - gnome-tweaks
        - wget
        - flatpak
        - whois
        - python3-venv
        - curl
        - neovim
        - gtop
        - ansible
        - pandoc
        # GNOME dev related tools
        - libgirepository1.0-dev
        - gcc
        - libcairo2-dev
        - pkg-config
        - python3-dev
        - gir1.2-gtk-4.0
    snaps:
        - name: thunderbird
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    late-commands:
        - curtin in-target -- flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        - curtin in-target -- flatpak install -y --noninteractive flathub org.dupot.easyflatpak
    updates: all
    shutdown: reboot

