#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Daniel Bastos'
        hostname: ubuntu-desktop
        username: daniel
        password: '$y$j9T$5pAN1/ncUajtWgf7sXvvz0$QL5UPd8QwMI0KVtUHuZ8wmTj35jMLQ1DK7KR2GI/0R4'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - git
        - gnome-tweaks
        - wget
        - flatpak
        - whois
        - python3-venv
        - curl
        - neovim
        - gtop
    snaps:
        - name: thunderbird
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

